<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SkillSeeder extends Seeder
{
    public function run(): void
    {
        $now = now();

        $skills = [
            [
                'code' => 'SKL-001',
                'level' => 1,
                'animal' => 'ひよこ',
                'level_label' => 'ひよこ級',
                'name' => 'アリーナ壁から壁まで',
                'alternate_name' => 'Arena wall-to-wall ride',
                'category' => 'ソロ',
                'performance_type' => 'ソロ',
                'skill_family' => '走行',
                'promotion_test' => 'アリーナの壁から反対側の壁まで走行する',
                'pass_criteria' => '補助なし・途中降車なしで反対側まで到達する',
                'official_reference' => 'クラブ昇級表',
                'min_duration' => 8,
                'default_duration' => 12,
                'max_duration' => 20,
                'showiness' => 1,
                'sync_load' => 1,
                'people' => '1人',
                'trajectory' => '直線',
                'recommended_scene' => '導入',
                'description' => 'アリーナの壁から反対側の壁まで走行する。補助なし・途中降車なしで反対側まで到達する',
                'tips' => '進行方向を見て、サドルに体重を預けて小さくこぐ。',
                'caution' => '安全確保のため壁へ正面衝突しない停止位置を決める。',
                'evidence_type' => 'ユーザー提供昇級表',
                'source_ids' => ['U01', 'S01'],
                'avatar_path' => 'images/skills/level-01.png',
                'movie_path' => null,
                'is_active' => true,
            ],
            [
                'code' => 'SKL-002',
                'level' => 2,
                'animal' => 'ひよこ',
                'level_label' => 'ひよこ級',
                'name' => 'アリーナ1周',
                'alternate_name' => 'Arena one-lap ride',
                'category' => 'ソロ',
                'performance_type' => 'ソロ',
                'skill_family' => '走行',
                'promotion_test' => 'アリーナを1周する',
                'pass_criteria' => '補助なし・途中降車なしで指定コースを1周する',
                'official_reference' => 'クラブ昇級表',
                'min_duration' => 20,
                'default_duration' => 30,
                'max_duration' => 45,
                'showiness' => 1,
                'sync_load' => 1,
                'people' => '1人',
                'trajectory' => '周回',
                'recommended_scene' => '基礎',
                'description' => 'アリーナを1周する。補助なし・途中降車なしで指定コースを1周する',
                'tips' => '直線では一定速度、角では早めに視線を出口へ向ける。',
                'caution' => '壁との距離を一定にし、急な方向転換を避ける。',
                'evidence_type' => 'ユーザー提供昇級表',
                'source_ids' => ['U01', 'S01'],
                'avatar_path' => 'images/skills/level-02.png',
                'movie_path' => null,
                'is_active' => true,
            ],
            [
                'code' => 'SKL-003',
                'level' => 3,
                'animal' => 'ひよこ',
                'level_label' => 'ひよこ級',
                'name' => 'アリーナ2周',
                'alternate_name' => 'Arena two-lap ride',
                'category' => 'ソロ',
                'performance_type' => 'ソロ',
                'skill_family' => '走行',
                'promotion_test' => 'アリーナを2周する',
                'pass_criteria' => '補助なし・途中降車なしで指定コースを2周する',
                'official_reference' => 'クラブ昇級表',
                'min_duration' => 40,
                'default_duration' => 60,
                'max_duration' => 90,
                'showiness' => 1,
                'sync_load' => 1,
                'people' => '1人',
                'trajectory' => '周回',
                'recommended_scene' => '基礎',
                'description' => 'アリーナを2周する。補助なし・途中降車なしで指定コースを2周する',
                'tips' => 'ペースを上げすぎず、1周目と2周目の軌道をそろえる。',
                'caution' => '疲れて上体が左右に揺れないようにする。',
                'evidence_type' => 'ユーザー提供昇級表',
                'source_ids' => ['U01', 'S01'],
                'avatar_path' => 'images/skills/level-03.png',
                'movie_path' => null,
                'is_active' => true,
            ],
            [
                'code' => 'SKL-004',
                'level' => 4,
                'animal' => 'ひよこ',
                'level_label' => 'ひよこ級',
                'name' => 'アリーナ3周',
                'alternate_name' => 'Arena three-lap ride',
                'category' => 'ソロ',
                'performance_type' => 'ソロ',
                'skill_family' => '走行',
                'promotion_test' => 'アリーナを3周する',
                'pass_criteria' => '補助なし・途中降車なしで指定コースを3周する',
                'official_reference' => 'クラブ昇級表',
                'min_duration' => 60,
                'default_duration' => 90,
                'max_duration' => 135,
                'showiness' => 1,
                'sync_load' => 1,
                'people' => '1人',
                'trajectory' => '周回',
                'recommended_scene' => '基礎',
                'description' => 'アリーナを3周する。補助なし・途中降車なしで指定コースを3周する',
                'tips' => '呼吸とペースを一定にして、角の前で軽く減速する。',
                'caution' => '他の練習者と走路が重ならないようにする。',
                'evidence_type' => 'ユーザー提供昇級表',
                'source_ids' => ['U01', 'S01'],
                'avatar_path' => 'images/skills/level-04.png',
                'movie_path' => null,
                'is_active' => true,
            ],
            [
                'code' => 'SKL-005',
                'level' => 5,
                'animal' => 'ひよこ',
                'level_label' => 'ひよこ級',
                'name' => '1周から逆回り1周',
                'alternate_name' => 'One lap then reverse direction',
                'category' => 'ソロ',
                'performance_type' => 'ソロ',
                'skill_family' => '方向転換',
                'promotion_test' => '1周後に方向を変えて逆回りを1周する',
                'pass_criteria' => '途中降車せず、決めた位置で安全に方向転換して両方向を1周する',
                'official_reference' => 'クラブ昇級表',
                'min_duration' => 45,
                'default_duration' => 65,
                'max_duration' => 100,
                'showiness' => 2,
                'sync_load' => 1,
                'people' => '1人',
                'trajectory' => '周回・折返し',
                'recommended_scene' => '基礎',
                'description' => '1周後に方向を変えて逆回りを1周する。途中降車せず、決めた位置で安全に方向転換して両方向を1周する',
                'tips' => '方向転換前に減速し、視線を逆回りの出口へ先に送る。',
                'caution' => '転換場所を固定し、後方の人と接触しないようにする。',
                'evidence_type' => 'ユーザー提供昇級表',
                'source_ids' => ['U01', 'S01'],
                'avatar_path' => 'images/skills/level-05.png',
                'movie_path' => null,
                'is_active' => true,
            ],
            [
                'code' => 'SKL-006',
                'level' => 6,
                'animal' => 'リス',
                'level_label' => 'リス級',
                'name' => 'ジグザグコース',
                'alternate_name' => 'Zigzag course',
                'category' => 'ソロ',
                'performance_type' => 'ソロ',
                'skill_family' => '走行',
                'promotion_test' => '指定されたジグザグコースを走行する',
                'pass_criteria' => 'マーカーへ接触せず、途中降車なしでゴールする',
                'official_reference' => 'クラブ昇級表',
                'min_duration' => 12,
                'default_duration' => 18,
                'max_duration' => 30,
                'showiness' => 2,
                'sync_load' => 1,
                'people' => '1人',
                'trajectory' => 'ジグザグ',
                'recommended_scene' => '基礎',
                'description' => '指定されたジグザグコースを走行する。マーカーへ接触せず、途中降車なしでゴールする',
                'tips' => '次のマーカーを早めに見て、肩と腰を進行方向へ向ける。',
                'caution' => 'マーカー間隔は技能に合わせ、狭くしすぎない。',
                'evidence_type' => 'ユーザー提供昇級表',
                'source_ids' => ['U01', 'S01'],
                'avatar_path' => 'images/skills/level-06.png',
                'movie_path' => null,
                'is_active' => true,
            ],
            [
                'code' => 'SKL-007',
                'level' => 7,
                'animal' => 'リス',
                'level_label' => 'リス級',
                'name' => '右まわり3周',
                'alternate_name' => 'Three clockwise circles',
                'category' => 'ソロ',
                'performance_type' => 'ソロ',
                'skill_family' => '旋回',
                'promotion_test' => '右回りで同じ円を3周する',
                'pass_criteria' => '円から大きく外れず、途中降車なしで3周する',
                'official_reference' => 'クラブ昇級表',
                'min_duration' => 12,
                'default_duration' => 18,
                'max_duration' => 28,
                'showiness' => 2,
                'sync_load' => 1,
                'people' => '1人',
                'trajectory' => '右円',
                'recommended_scene' => '基礎',
                'description' => '右回りで同じ円を3周する。円から大きく外れず、途中降車なしで3周する',
                'tips' => '円の中心を見るのではなく、少し先の進行方向を見る。',
                'caution' => '内側へ急に倒し込まず、一定半径を保つ。',
                'evidence_type' => 'ユーザー提供昇級表',
                'source_ids' => ['U01', 'S01'],
                'avatar_path' => 'images/skills/level-07.png',
                'movie_path' => null,
                'is_active' => true,
            ],
            [
                'code' => 'SKL-008',
                'level' => 8,
                'animal' => 'リス',
                'level_label' => 'リス級',
                'name' => '左まわり3周',
                'alternate_name' => 'Three counterclockwise circles',
                'category' => 'ソロ',
                'performance_type' => 'ソロ',
                'skill_family' => '旋回',
                'promotion_test' => '左回りで同じ円を3周する',
                'pass_criteria' => '円から大きく外れず、途中降車なしで3周する',
                'official_reference' => 'クラブ昇級表',
                'min_duration' => 12,
                'default_duration' => 18,
                'max_duration' => 28,
                'showiness' => 2,
                'sync_load' => 1,
                'people' => '1人',
                'trajectory' => '左円',
                'recommended_scene' => '基礎',
                'description' => '左回りで同じ円を3周する。円から大きく外れず、途中降車なしで3周する',
                'tips' => '苦手側ほどゆっくり入り、視線と肩を円の出口へ向ける。',
                'caution' => '左右差を確認し、無理に小さい円へしない。',
                'evidence_type' => 'ユーザー提供昇級表',
                'source_ids' => ['U01', 'S01'],
                'avatar_path' => 'images/skills/level-08.png',
                'movie_path' => null,
                'is_active' => true,
            ],
            [
                'code' => 'SKL-009',
                'level' => 9,
                'animal' => 'リス',
                'level_label' => 'リス級',
                'name' => '8の字ひこうき（大）',
                'alternate_name' => 'Large figure-eight airplane',
                'category' => 'ソロ',
                'performance_type' => 'ソロ',
                'skill_family' => '走行',
                'promotion_test' => '腕を広げ、大きな8の字を走行する',
                'pass_criteria' => '左右の円を同程度の大きさで描き、途中降車なしで1周する',
                'official_reference' => 'クラブ昇級表',
                'min_duration' => 18,
                'default_duration' => 25,
                'max_duration' => 40,
                'showiness' => 3,
                'sync_load' => 1,
                'people' => '1人',
                'trajectory' => '大きな8の字',
                'recommended_scene' => '見せ場',
                'description' => '腕を広げ、大きな8の字を走行する。左右の円を同程度の大きさで描き、途中降車なしで1周する',
                'tips' => '腕を肩の高さに広げ、交点で次の円へ視線を切り替える。',
                'caution' => '交点で他者と走路が重ならないようにする。',
                'evidence_type' => 'ユーザー提供昇級表',
                'source_ids' => ['U01', 'S01'],
                'avatar_path' => 'images/skills/level-09.png',
                'movie_path' => null,
                'is_active' => true,
            ],
            [
                'code' => 'SKL-010',
                'level' => 10,
                'animal' => 'リス',
                'level_label' => 'リス級',
                'name' => '8の字ひこうき（小）',
                'alternate_name' => 'Small figure-eight airplane',
                'category' => 'ソロ',
                'performance_type' => 'ソロ',
                'skill_family' => '走行',
                'promotion_test' => '腕を広げ、小さな8の字を走行する',
                'pass_criteria' => '決めた範囲内で左右の小円を描き、途中降車なしで1周する',
                'official_reference' => 'クラブ昇級表',
                'min_duration' => 12,
                'default_duration' => 18,
                'max_duration' => 30,
                'showiness' => 3,
                'sync_load' => 1,
                'people' => '1人',
                'trajectory' => '小さな8の字',
                'recommended_scene' => '見せ場',
                'description' => '腕を広げ、小さな8の字を走行する。決めた範囲内で左右の小円を描き、途中降車なしで1周する',
                'tips' => '速度を落とし、腰を車輪の上に残したまま細かく旋回する。',
                'caution' => '小さくしすぎると転倒しやすいため基準線を設定する。',
                'evidence_type' => 'ユーザー提供昇級表',
                'source_ids' => ['U01', 'S01'],
                'avatar_path' => 'images/skills/level-10.png',
                'movie_path' => null,
                'is_active' => true,
            ],
            [
                'code' => 'SKL-011',
                'level' => 11,
                'animal' => 'うさぎ',
                'level_label' => 'うさぎ級',
                'name' => '空中乗り',
                'alternate_name' => 'Free mount',
                'category' => 'ソロ',
                'performance_type' => 'ソロ',
                'skill_family' => '乗降',
                'promotion_test' => '支えを使わずに空中乗りで乗車する',
                'pass_criteria' => '3回以内の試技で1回成功し、乗車後3m以上走行する',
                'official_reference' => 'クラブ昇級表／IUF基礎技能',
                'min_duration' => 3,
                'default_duration' => 5,
                'max_duration' => 8,
                'showiness' => 3,
                'sync_load' => 1,
                'people' => '1人',
                'trajectory' => '静止→前進',
                'recommended_scene' => '導入',
                'description' => '支えを使わずに空中乗りで乗車する。3回以内の試技で1回成功し、乗車後3m以上走行する',
                'tips' => 'サドルを体に固定し、後ろ足で強く踏み込みすぎず上体を前へ運ぶ。',
                'caution' => 'クラブ内で空中乗りの動作定義と開始姿勢を統一する。',
                'evidence_type' => 'ユーザー提供昇級表',
                'source_ids' => ['U01', 'S01'],
                'avatar_path' => 'images/skills/level-11.png',
                'movie_path' => null,
                'is_active' => true,
            ],
            [
                'code' => 'SKL-012',
                'level' => 12,
                'animal' => 'うさぎ',
                'level_label' => 'うさぎ級',
                'name' => 'アイドリング3回',
                'alternate_name' => 'Three idles',
                'category' => 'ソロ',
                'performance_type' => 'ソロ',
                'skill_family' => '定点',
                'promotion_test' => '前→後ろ→前を1回としてアイドリングを3回行う',
                'pass_criteria' => '補助なしで3回連続し、その後安全に走り出すか降車する',
                'official_reference' => 'クラブ昇級表／IUF基礎技能',
                'min_duration' => 4,
                'default_duration' => 6,
                'max_duration' => 10,
                'showiness' => 2,
                'sync_load' => 1,
                'people' => '1人',
                'trajectory' => '定点',
                'recommended_scene' => '基礎',
                'description' => '前→後ろ→前を1回としてアイドリングを3回行う。補助なしで3回連続し、その後安全に走り出すか降車する',
                'tips' => '下側の足を中心に使い、車輪の往復幅を小さくする。',
                'caution' => '上体だけを大きく振って回数を作らない。',
                'evidence_type' => 'ユーザー提供昇級表',
                'source_ids' => ['U01', 'S01', 'S02'],
                'avatar_path' => 'images/skills/level-12.png',
                'movie_path' => null,
                'is_active' => true,
            ],
            [
                'code' => 'SKL-013',
                'level' => 13,
                'animal' => 'うさぎ',
                'level_label' => 'うさぎ級',
                'name' => 'バック走行5m',
                'alternate_name' => 'Backward riding 5 m',
                'category' => 'ソロ',
                'performance_type' => 'ソロ',
                'skill_family' => '走行',
                'promotion_test' => '後ろ向きに5m走行する',
                'pass_criteria' => '指定線から5mを補助なし・途中降車なしで走行する',
                'official_reference' => 'クラブ昇級表／IUF基礎技能',
                'min_duration' => 6,
                'default_duration' => 9,
                'max_duration' => 15,
                'showiness' => 2,
                'sync_load' => 1,
                'people' => '1人',
                'trajectory' => 'バック直線',
                'recommended_scene' => '基礎',
                'description' => '後ろ向きに5m走行する。指定線から5mを補助なし・途中降車なしで走行する',
                'tips' => '腰を車軸上に置き、肩越しに進路を短く確認する。',
                'caution' => '後方走路を分離し、補助者を配置する。',
                'evidence_type' => 'ユーザー提供昇級表',
                'source_ids' => ['U01', 'S01'],
                'avatar_path' => 'images/skills/level-13.png',
                'movie_path' => null,
                'is_active' => true,
            ],
            [
                'code' => 'SKL-014',
                'level' => 14,
                'animal' => 'うさぎ',
                'level_label' => 'うさぎ級',
                'name' => 'アイドリング10回',
                'alternate_name' => 'Ten idles',
                'category' => 'ソロ',
                'performance_type' => 'ソロ',
                'skill_family' => '定点',
                'promotion_test' => 'アイドリングを10回行う',
                'pass_criteria' => '補助なしで10回連続し、上体と車輪が基準範囲から大きく外れない',
                'official_reference' => 'クラブ昇級表／IUF基礎技能',
                'min_duration' => 8,
                'default_duration' => 12,
                'max_duration' => 18,
                'showiness' => 2,
                'sync_load' => 1,
                'people' => '1人',
                'trajectory' => '定点',
                'recommended_scene' => '基礎',
                'description' => 'アイドリングを10回行う。補助なしで10回連続し、上体と車輪が基準範囲から大きく外れない',
                'tips' => '往復のテンポと幅を一定にし、腰を中央に残す。',
                'caution' => '回数は前→後ろ→前を1回として数える。',
                'evidence_type' => 'ユーザー提供昇級表',
                'source_ids' => ['U01', 'S01', 'S02'],
                'avatar_path' => 'images/skills/level-14.png',
                'movie_path' => null,
                'is_active' => true,
            ],
            [
                'code' => 'SKL-015',
                'level' => 15,
                'animal' => 'うさぎ',
                'level_label' => 'うさぎ級',
                'name' => 'バック走行10m',
                'alternate_name' => 'Backward riding 10 m',
                'category' => 'ソロ',
                'performance_type' => 'ソロ',
                'skill_family' => '走行',
                'promotion_test' => '後ろ向きに10m走行する',
                'pass_criteria' => '指定線から10mを補助なし・途中降車なしで走行する',
                'official_reference' => 'クラブ昇級表／IUF基礎技能',
                'min_duration' => 10,
                'default_duration' => 15,
                'max_duration' => 24,
                'showiness' => 2,
                'sync_load' => 1,
                'people' => '1人',
                'trajectory' => 'バック直線',
                'recommended_scene' => '基礎',
                'description' => '後ろ向きに10m走行する。指定線から10mを補助なし・途中降車なしで走行する',
                'tips' => '一定速度を保ち、確認する肩の方向を決めておく。',
                'caution' => '十分な後方スペースと停止位置を確保する。',
                'evidence_type' => 'ユーザー提供昇級表',
                'source_ids' => ['U01', 'S01'],
                'avatar_path' => 'images/skills/level-15.png',
                'movie_path' => null,
                'is_active' => true,
            ],
            [
                'code' => 'SKL-016',
                'level' => 16,
                'animal' => 'きつね',
                'level_label' => 'きつね級',
                'name' => 'アイドリング20回',
                'alternate_name' => 'Twenty idles',
                'category' => 'ソロ',
                'performance_type' => 'ソロ',
                'skill_family' => '定点',
                'promotion_test' => 'アイドリングを20回行う',
                'pass_criteria' => '補助なしで20回連続し、往復幅と姿勢を保つ',
                'official_reference' => 'クラブ昇級表／IUF基礎技能',
                'min_duration' => 14,
                'default_duration' => 20,
                'max_duration' => 30,
                'showiness' => 3,
                'sync_load' => 1,
                'people' => '1人',
                'trajectory' => '定点',
                'recommended_scene' => 'つなぎ',
                'description' => 'アイドリングを20回行う。補助なしで20回連続し、往復幅と姿勢を保つ',
                'tips' => '足だけで急いで動かさず、一定のリズムで呼吸する。',
                'caution' => '回数を数える人と開始・終了を確認する。',
                'evidence_type' => 'ユーザー提供昇級表',
                'source_ids' => ['U01', 'S01', 'S02'],
                'avatar_path' => 'images/skills/level-16.png',
                'movie_path' => null,
                'is_active' => true,
            ],
            [
                'code' => 'SKL-017',
                'level' => 17,
                'animal' => 'きつね',
                'level_label' => 'きつね級',
                'name' => 'バック走行20m',
                'alternate_name' => 'Backward riding 20 m',
                'category' => 'ソロ',
                'performance_type' => 'ソロ',
                'skill_family' => '走行',
                'promotion_test' => '後ろ向きに20m走行する',
                'pass_criteria' => '指定コースを補助なし・途中降車なしで20m走行する',
                'official_reference' => 'クラブ昇級表／IUF基礎技能',
                'min_duration' => 18,
                'default_duration' => 28,
                'max_duration' => 45,
                'showiness' => 3,
                'sync_load' => 1,
                'people' => '1人',
                'trajectory' => 'バック直線',
                'recommended_scene' => 'つなぎ',
                'description' => '後ろ向きに20m走行する。指定コースを補助なし・途中降車なしで20m走行する',
                'tips' => '小さく滑らかにこぎ、進路確認後は視線を正面近くへ戻す。',
                'caution' => 'コース外側に補助者を置き、前進練習と時間を分ける。',
                'evidence_type' => 'ユーザー提供昇級表',
                'source_ids' => ['U01', 'S01'],
                'avatar_path' => 'images/skills/level-17.png',
                'movie_path' => null,
                'is_active' => true,
            ],
            [
                'code' => 'SKL-018',
                'level' => 18,
                'animal' => 'きつね',
                'level_label' => 'きつね級',
                'name' => 'あめ玉スピン',
                'alternate_name' => 'Candy spin',
                'category' => 'ソロ',
                'performance_type' => 'ソロ',
                'skill_family' => '回転',
                'promotion_test' => 'クラブで定めたあめ玉スピンを行う',
                'pass_criteria' => '決めた開始姿勢・回転数・終了姿勢を崩さず完了する',
                'official_reference' => 'クラブ昇級表',
                'min_duration' => 5,
                'default_duration' => 8,
                'max_duration' => 12,
                'showiness' => 4,
                'sync_load' => 1,
                'people' => '1人',
                'trajectory' => '小円・定点',
                'recommended_scene' => '見せ場',
                'description' => 'クラブで定めたあめ玉スピンを行う。決めた開始姿勢・回転数・終了姿勢を崩さず完了する',
                'tips' => '進入速度を整え、腕を閉じるタイミングと回転軸をそろえる。',
                'caution' => 'クラブ独自呼称のため、見本動画で判定基準を共有する。',
                'evidence_type' => 'ユーザー提供昇級表',
                'source_ids' => ['U01'],
                'avatar_path' => 'images/skills/level-18.png',
                'movie_path' => null,
                'is_active' => true,
            ],
            [
                'code' => 'SKL-019',
                'level' => 19,
                'animal' => 'きつね',
                'level_label' => 'きつね級',
                'name' => '3分間乗り続ける（ラン）',
                'alternate_name' => 'Three-minute continuous ride',
                'category' => 'ソロ',
                'performance_type' => 'ソロ',
                'skill_family' => '持久走',
                'promotion_test' => '3分間、一輪車に乗り続ける',
                'pass_criteria' => '指定エリア内で途中降車せず3分間走行を継続する',
                'official_reference' => 'クラブ昇級表',
                'min_duration' => 180,
                'default_duration' => 180,
                'max_duration' => 190,
                'showiness' => 2,
                'sync_load' => 1,
                'people' => '1人',
                'trajectory' => '周回・自由走行',
                'recommended_scene' => '基礎',
                'description' => '3分間、一輪車に乗り続ける。指定エリア内で途中降車せず3分間走行を継続する',
                'tips' => '最初から速く走らず、呼吸できる一定ペースを保つ。',
                'caution' => '混雑時は周回方向を統一し、水分と体調を確認する。',
                'evidence_type' => 'ユーザー提供昇級表',
                'source_ids' => ['U01'],
                'avatar_path' => 'images/skills/level-19.png',
                'movie_path' => null,
                'is_active' => true,
            ],
            [
                'code' => 'SKL-020',
                'level' => 20,
                'animal' => 'きつね',
                'level_label' => 'きつね級',
                'name' => 'ホッピング1回',
                'alternate_name' => 'One hop',
                'category' => 'ソロ',
                'performance_type' => 'ソロ',
                'skill_family' => '跳躍',
                'promotion_test' => 'その場でホッピングを1回行う',
                'pass_criteria' => 'ペダルを水平にし、補助なしで1回跳んで着地を保つ',
                'official_reference' => 'クラブ昇級表／IUF基礎技能',
                'min_duration' => 2,
                'default_duration' => 3,
                'max_duration' => 5,
                'showiness' => 3,
                'sync_load' => 1,
                'people' => '1人',
                'trajectory' => '定点',
                'recommended_scene' => 'アクセント',
                'description' => 'その場でホッピングを1回行う。ペダルを水平にし、補助なしで1回跳んで着地を保つ',
                'tips' => 'サドルを保持し、足首と膝を使って真上へ小さく跳ぶ。',
                'caution' => '着地時にペダルから足が外れない高さで行う。',
                'evidence_type' => 'ユーザー提供昇級表',
                'source_ids' => ['U01', 'S01', 'S02'],
                'avatar_path' => 'images/skills/level-20.png',
                'movie_path' => null,
                'is_active' => true,
            ],
            [
                'code' => 'SKL-021',
                'level' => 21,
                'animal' => 'トラ',
                'level_label' => 'トラ級',
                'name' => 'アイドリング30回',
                'alternate_name' => 'Thirty idles',
                'category' => 'ソロ',
                'performance_type' => 'ソロ',
                'skill_family' => '定点',
                'promotion_test' => 'アイドリングを30回行う',
                'pass_criteria' => '補助なしで30回連続し、基準範囲内で姿勢を保つ',
                'official_reference' => 'クラブ昇級表／IUF基礎技能',
                'min_duration' => 20,
                'default_duration' => 30,
                'max_duration' => 45,
                'showiness' => 3,
                'sync_load' => 1,
                'people' => '1人',
                'trajectory' => '定点',
                'recommended_scene' => 'つなぎ',
                'description' => 'アイドリングを30回行う。補助なしで30回連続し、基準範囲内で姿勢を保つ',
                'tips' => '疲れても往復幅を広げず、同じテンポを続ける。',
                'caution' => '回数よりも安全な終了と走り出しを優先する。',
                'evidence_type' => 'ユーザー提供昇級表',
                'source_ids' => ['U01', 'S01', 'S02'],
                'avatar_path' => 'images/skills/level-21.png',
                'movie_path' => null,
                'is_active' => true,
            ],
            [
                'code' => 'SKL-022',
                'level' => 22,
                'animal' => 'トラ',
                'level_label' => 'トラ級',
                'name' => 'バック走行30m',
                'alternate_name' => 'Backward riding 30 m',
                'category' => 'ソロ',
                'performance_type' => 'ソロ',
                'skill_family' => '走行',
                'promotion_test' => '後ろ向きに30m走行する',
                'pass_criteria' => '指定コースを補助なし・途中降車なしで30m走行する',
                'official_reference' => 'クラブ昇級表／IUF基礎技能',
                'min_duration' => 25,
                'default_duration' => 40,
                'max_duration' => 60,
                'showiness' => 3,
                'sync_load' => 1,
                'people' => '1人',
                'trajectory' => 'バック直線・周回',
                'recommended_scene' => '見せ場',
                'description' => '後ろ向きに30m走行する。指定コースを補助なし・途中降車なしで30m走行する',
                'tips' => '確認動作を小さくし、速度と直線性を一定に保つ。',
                'caution' => '後方専用レーンと停止合図を設定する。',
                'evidence_type' => 'ユーザー提供昇級表',
                'source_ids' => ['U01', 'S01'],
                'avatar_path' => 'images/skills/level-22.png',
                'movie_path' => null,
                'is_active' => true,
            ],
            [
                'code' => 'SKL-023',
                'level' => 23,
                'animal' => 'トラ',
                'level_label' => 'トラ級',
                'name' => '左右旋回と8の字',
                'alternate_name' => 'Circles and figure-eight sequence',
                'category' => 'ソロ',
                'performance_type' => 'ソロ',
                'skill_family' => '複合走行',
                'promotion_test' => '右回り3周→左回り3周→8の字ひこうき1周を連続する',
                'pass_criteria' => '順番どおり、途中降車なしで全コースを完了する',
                'official_reference' => 'クラブ昇級表',
                'min_duration' => 35,
                'default_duration' => 50,
                'max_duration' => 75,
                'showiness' => 4,
                'sync_load' => 1,
                'people' => '1人',
                'trajectory' => '右円→左円→8の字',
                'recommended_scene' => '見せ場',
                'description' => '右回り3周→左回り3周→8の字ひこうき1周を連続する。順番どおり、途中降車なしで全コースを完了する',
                'tips' => '技の切替地点を決め、次の軌道へ早めに視線を送る。',
                'caution' => 'コースを十分広く取り、切替時の急旋回を避ける。',
                'evidence_type' => 'ユーザー提供昇級表',
                'source_ids' => ['U01', 'S01'],
                'avatar_path' => 'images/skills/level-23.png',
                'movie_path' => null,
                'is_active' => true,
            ],
            [
                'code' => 'SKL-024',
                'level' => 24,
                'animal' => 'トラ',
                'level_label' => 'トラ級',
                'name' => 'アイドリング50回以上',
                'alternate_name' => 'Fifty or more idles',
                'category' => 'ソロ',
                'performance_type' => 'ソロ',
                'skill_family' => '定点',
                'promotion_test' => 'アイドリングを50回以上行う',
                'pass_criteria' => '補助なしで50回以上連続し、姿勢と往復幅を保つ',
                'official_reference' => 'クラブ昇級表／IUF基礎技能',
                'min_duration' => 32,
                'default_duration' => 50,
                'max_duration' => 75,
                'showiness' => 3,
                'sync_load' => 1,
                'people' => '1人',
                'trajectory' => '定点',
                'recommended_scene' => '見せ場',
                'description' => 'アイドリングを50回以上行う。補助なしで50回以上連続し、姿勢と往復幅を保つ',
                'tips' => '一定テンポで数え、上半身の力を抜いて軸を保つ。',
                'caution' => '疲労時に大きく傾いた場合は安全を優先して終了する。',
                'evidence_type' => 'ユーザー提供昇級表',
                'source_ids' => ['U01', 'S01', 'S02'],
                'avatar_path' => 'images/skills/level-24.png',
                'movie_path' => null,
                'is_active' => true,
            ],
            [
                'code' => 'SKL-025',
                'level' => 25,
                'animal' => 'トラ',
                'level_label' => 'トラ級',
                'name' => '横乗り',
                'alternate_name' => 'Side ride',
                'category' => 'ソロ',
                'performance_type' => 'ソロ',
                'skill_family' => '走行',
                'promotion_test' => '横乗りで指定距離を走行する',
                'pass_criteria' => 'クラブで定めた姿勢で3m以上進み、安全に終了する',
                'official_reference' => 'クラブ昇級表／IUF技能',
                'min_duration' => 5,
                'default_duration' => 8,
                'max_duration' => 14,
                'showiness' => 5,
                'sync_load' => 1,
                'people' => '1人',
                'trajectory' => '横移動・直線',
                'recommended_scene' => 'ピーク',
                'description' => '横乗りで指定距離を走行する。クラブで定めた姿勢で3m以上進み、安全に終了する',
                'tips' => '体と足の向きをそろえ、車輪と体の距離を一定にする。',
                'caution' => '上級技。補助者と十分な横幅を確保し、段階練習する。',
                'evidence_type' => 'ユーザー提供昇級表',
                'source_ids' => ['U01', 'S01', 'S02'],
                'avatar_path' => 'images/skills/level-25.png',
                'movie_path' => null,
                'is_active' => true,
            ],
            [
                'code' => 'SKL-026',
                'level' => 26,
                'animal' => 'トラ',
                'level_label' => 'トラ級',
                'name' => 'ホッピング3回',
                'alternate_name' => 'Three hops',
                'category' => 'ソロ',
                'performance_type' => 'ソロ',
                'skill_family' => '跳躍',
                'promotion_test' => 'その場でホッピングを3回連続する',
                'pass_criteria' => '補助なしで3回連続し、最後の着地を2秒保つ',
                'official_reference' => 'IUF基礎技能を簡略化',
                'min_duration' => 3,
                'default_duration' => 5,
                'max_duration' => 8,
                'showiness' => 3,
                'sync_load' => 1,
                'people' => '1人',
                'trajectory' => '定点',
                'recommended_scene' => 'アクセント',
                'description' => 'その場でホッピングを3回連続する。補助なしで3回連続し、最後の着地を2秒保つ',
                'tips' => '高さよりも着地位置とリズムをそろえる。',
                'caution' => 'ペダルを水平に保ち、サドルを強く引き上げすぎない。',
                'evidence_type' => '既存技一覧を統合した昇級案',
                'source_ids' => ['S01', 'S02'],
                'avatar_path' => 'images/skills/level-26.png',
                'movie_path' => null,
                'is_active' => true,
            ],
            [
                'code' => 'SKL-027',
                'level' => 27,
                'animal' => 'トラ',
                'level_label' => 'トラ級',
                'name' => 'ホッピング5回',
                'alternate_name' => 'Five hops',
                'category' => 'ソロ',
                'performance_type' => 'ソロ',
                'skill_family' => '跳躍',
                'promotion_test' => 'その場でホッピングを5回連続する',
                'pass_criteria' => '補助なしで5回連続し、同じ場所で終了する',
                'official_reference' => 'IUF基礎技能を簡略化',
                'min_duration' => 4,
                'default_duration' => 7,
                'max_duration' => 10,
                'showiness' => 3,
                'sync_load' => 1,
                'people' => '1人',
                'trajectory' => '定点',
                'recommended_scene' => 'アクセント',
                'description' => 'その場でホッピングを5回連続する。補助なしで5回連続し、同じ場所で終了する',
                'tips' => '膝と足首の小さな反発で一定リズムを作る。',
                'caution' => '着地音が大きくならない高さに調整する。',
                'evidence_type' => '既存技一覧を統合した昇級案',
                'source_ids' => ['S01', 'S02'],
                'avatar_path' => 'images/skills/level-27.png',
                'movie_path' => null,
                'is_active' => true,
            ],
            [
                'code' => 'SKL-028',
                'level' => 28,
                'animal' => 'トラ',
                'level_label' => 'トラ級',
                'name' => 'ホッピング10回',
                'alternate_name' => 'Ten hops',
                'category' => 'ソロ',
                'performance_type' => 'ソロ',
                'skill_family' => '跳躍',
                'promotion_test' => 'その場でホッピングを10回連続する',
                'pass_criteria' => '補助なしで10回連続し、基準円から出ない',
                'official_reference' => 'IUF基礎技能を簡略化',
                'min_duration' => 7,
                'default_duration' => 10,
                'max_duration' => 15,
                'showiness' => 4,
                'sync_load' => 1,
                'people' => '1人',
                'trajectory' => '定点',
                'recommended_scene' => '見せ場',
                'description' => 'その場でホッピングを10回連続する。補助なしで10回連続し、基準円から出ない',
                'tips' => '腕とサドル位置を固定し、毎回同じ高さで跳ぶ。',
                'caution' => '疲れて前後へ流れたら無理に続けない。',
                'evidence_type' => '既存技一覧を統合した昇級案',
                'source_ids' => ['S01', 'S02'],
                'avatar_path' => 'images/skills/level-28.png',
                'movie_path' => null,
                'is_active' => true,
            ],
            [
                'code' => 'SKL-029',
                'level' => 29,
                'animal' => 'トラ',
                'level_label' => 'トラ級',
                'name' => '前進ホッピング3m',
                'alternate_name' => 'Forward hopping 3 m',
                'category' => 'ソロ',
                'performance_type' => 'ソロ',
                'skill_family' => '跳躍',
                'promotion_test' => 'ホッピングで前へ3m移動する',
                'pass_criteria' => '指定幅のレーン内を、途中降車なしで3m進む',
                'official_reference' => '既存技一覧のホッピングを段階化',
                'min_duration' => 6,
                'default_duration' => 10,
                'max_duration' => 15,
                'showiness' => 4,
                'sync_load' => 1,
                'people' => '1人',
                'trajectory' => '前進直線',
                'recommended_scene' => '見せ場',
                'description' => 'ホッピングで前へ3m移動する。指定幅のレーン内を、途中降車なしで3m進む',
                'tips' => '真上への跳躍に少しだけ前方向の重心移動を加える。',
                'caution' => '着地ごとに急いで前へ倒れ込まない。',
                'evidence_type' => '既存技一覧を統合した昇級案',
                'source_ids' => ['S01', 'S02'],
                'avatar_path' => 'images/skills/level-29.png',
                'movie_path' => null,
                'is_active' => true,
            ],
            [
                'code' => 'SKL-030',
                'level' => 30,
                'animal' => 'トラ',
                'level_label' => 'トラ級',
                'name' => 'ホッピング90度ターン',
                'alternate_name' => 'Hopping 90-degree turn',
                'category' => 'ソロ',
                'performance_type' => 'ソロ',
                'skill_family' => '跳躍',
                'promotion_test' => 'ホッピングで90度方向転換する',
                'pass_criteria' => '左右どちらか指定された方向へ90度回り、着地を保つ',
                'official_reference' => '既存技一覧のホップツイストを簡略化',
                'min_duration' => 3,
                'default_duration' => 5,
                'max_duration' => 8,
                'showiness' => 4,
                'sync_load' => 1,
                'people' => '1人',
                'trajectory' => '定点・90度転換',
                'recommended_scene' => 'アクセント',
                'description' => 'ホッピングで90度方向転換する。左右どちらか指定された方向へ90度回り、着地を保つ',
                'tips' => '跳ぶ前に肩を少し準備し、体と一輪車を一体で回す。',
                'caution' => '左右を別々に練習し、回しすぎない。',
                'evidence_type' => '既存技一覧を統合した昇級案',
                'source_ids' => ['S01', 'S02'],
                'avatar_path' => 'images/skills/level-30.png',
                'movie_path' => null,
                'is_active' => true,
            ],
            [
                'code' => 'SKL-031',
                'level' => 31,
                'animal' => 'トラ',
                'level_label' => 'トラ級',
                'name' => '片足走行5m',
                'alternate_name' => 'One-foot riding 5 m',
                'category' => 'ソロ',
                'performance_type' => 'ソロ',
                'skill_family' => '片足',
                'promotion_test' => '片足走行で5m進む',
                'pass_criteria' => '遊脚をフレームへ置き、途中降車なしで5m走行する',
                'official_reference' => '既存技一覧を短距離化',
                'min_duration' => 6,
                'default_duration' => 10,
                'max_duration' => 16,
                'showiness' => 4,
                'sync_load' => 1,
                'people' => '1人',
                'trajectory' => '直線',
                'recommended_scene' => '見せ場',
                'description' => '片足走行で5m進む。遊脚をフレームへ置き、途中降車なしで5m走行する',
                'tips' => '軸足で円を描くようにこぎ、遊脚を静かに置く。',
                'caution' => '通常走行から急に減速せず片足へ移行する。',
                'evidence_type' => '既存技一覧を統合した昇級案',
                'source_ids' => ['S01', 'S02'],
                'avatar_path' => 'images/skills/level-31.png',
                'movie_path' => null,
                'is_active' => true,
            ],
            [
                'code' => 'SKL-032',
                'level' => 32,
                'animal' => 'トラ',
                'level_label' => 'トラ級',
                'name' => '片足走行10m',
                'alternate_name' => 'One-foot riding 10 m',
                'category' => 'ソロ',
                'performance_type' => 'ソロ',
                'skill_family' => '片足',
                'promotion_test' => '片足走行で10m進む',
                'pass_criteria' => '途中降車なしで10m走行し、両足走行へ戻る',
                'official_reference' => '既存技一覧を統合',
                'min_duration' => 10,
                'default_duration' => 15,
                'max_duration' => 24,
                'showiness' => 4,
                'sync_load' => 1,
                'people' => '1人',
                'trajectory' => '直線',
                'recommended_scene' => '見せ場',
                'description' => '片足走行で10m進む。途中降車なしで10m走行し、両足走行へ戻る',
                'tips' => '軸足の踏力と上体の形を変えずに距離を伸ばす。',
                'caution' => 'ペダルへ戻す位置を事前に練習する。',
                'evidence_type' => '既存技一覧を統合した昇級案',
                'source_ids' => ['S01', 'S02'],
                'avatar_path' => 'images/skills/level-32.png',
                'movie_path' => null,
                'is_active' => true,
            ],
            [
                'code' => 'SKL-033',
                'level' => 33,
                'animal' => 'トラ',
                'level_label' => 'トラ級',
                'name' => 'タイヤ乗り3m',
                'alternate_name' => 'Wheel walk 3 m',
                'category' => 'ソロ',
                'performance_type' => 'ソロ',
                'skill_family' => 'タイヤ操作',
                'promotion_test' => 'タイヤ乗りで3m進む',
                'pass_criteria' => '足でタイヤを送り、途中降車なしで3m進む',
                'official_reference' => '既存技一覧を短距離化',
                'min_duration' => 7,
                'default_duration' => 11,
                'max_duration' => 18,
                'showiness' => 4,
                'sync_load' => 1,
                'people' => '1人',
                'trajectory' => '直線',
                'recommended_scene' => '見せ場',
                'description' => 'タイヤ乗りで3m進む。足でタイヤを送り、途中降車なしで3m進む',
                'tips' => '足裏全体でタイヤを送り、上体を少し後ろへ保つ。',
                'caution' => '足を詰めすぎず、最初は補助者のそばで行う。',
                'evidence_type' => '既存技一覧を統合した昇級案',
                'source_ids' => ['S01', 'S02'],
                'avatar_path' => 'images/skills/level-33.png',
                'movie_path' => null,
                'is_active' => true,
            ],
            [
                'code' => 'SKL-034',
                'level' => 34,
                'animal' => 'トラ',
                'level_label' => 'トラ級',
                'name' => 'タイヤ乗り5m',
                'alternate_name' => 'Wheel walk 5 m',
                'category' => 'ソロ',
                'performance_type' => 'ソロ',
                'skill_family' => 'タイヤ操作',
                'promotion_test' => 'タイヤ乗りで5m進む',
                'pass_criteria' => '途中降車なしで5m進み、ペダルへ戻る',
                'official_reference' => '既存技一覧を統合',
                'min_duration' => 9,
                'default_duration' => 14,
                'max_duration' => 22,
                'showiness' => 4,
                'sync_load' => 1,
                'people' => '1人',
                'trajectory' => '直線',
                'recommended_scene' => '見せ場',
                'description' => 'タイヤ乗りで5m進む。途中降車なしで5m進み、ペダルへ戻る',
                'tips' => 'タイヤを送る幅とテンポを一定にする。',
                'caution' => 'ペダル復帰までを1つの試技として練習する。',
                'evidence_type' => '既存技一覧を統合した昇級案',
                'source_ids' => ['S01', 'S02'],
                'avatar_path' => 'images/skills/level-34.png',
                'movie_path' => null,
                'is_active' => true,
            ],
            [
                'code' => 'SKL-035',
                'level' => 35,
                'animal' => 'トラ',
                'level_label' => 'トラ級',
                'name' => 'タイヤ乗り10m',
                'alternate_name' => 'Wheel walk 10 m',
                'category' => 'ソロ',
                'performance_type' => 'ソロ',
                'skill_family' => 'タイヤ操作',
                'promotion_test' => 'タイヤ乗りで10m進む',
                'pass_criteria' => '途中降車なしで10m進み、安定してペダルへ戻る',
                'official_reference' => '既存技一覧を統合',
                'min_duration' => 14,
                'default_duration' => 20,
                'max_duration' => 30,
                'showiness' => 4,
                'sync_load' => 1,
                'people' => '1人',
                'trajectory' => '直線',
                'recommended_scene' => 'ピーク',
                'description' => 'タイヤ乗りで10m進む。途中降車なしで10m進み、安定してペダルへ戻る',
                'tips' => '足の送りを急がず、フレームの角度を一定に保つ。',
                'caution' => '復帰位置を見下ろしすぎて上体を崩さない。',
                'evidence_type' => '既存技一覧を統合した昇級案',
                'source_ids' => ['S01', 'S02'],
                'avatar_path' => 'images/skills/level-35.png',
                'movie_path' => null,
                'is_active' => true,
            ],
            [
                'code' => 'SKL-036',
                'level' => 36,
                'animal' => 'トラ',
                'level_label' => 'トラ級',
                'name' => 'サドル前出し5m',
                'alternate_name' => 'Seat in front 5 m',
                'category' => 'ソロ',
                'performance_type' => 'ソロ',
                'skill_family' => 'サドル操作',
                'promotion_test' => 'サドルを前へ出して5m走行する',
                'pass_criteria' => '指定姿勢で5m進み、サドルを戻して走行を続ける',
                'official_reference' => '既存技一覧を統合',
                'min_duration' => 8,
                'default_duration' => 12,
                'max_duration' => 20,
                'showiness' => 4,
                'sync_load' => 1,
                'people' => '1人',
                'trajectory' => '直線',
                'recommended_scene' => '見せ場',
                'description' => 'サドルを前へ出して5m走行する。指定姿勢で5m進み、サドルを戻して走行を続ける',
                'tips' => '腰を車軸上に保ち、腕で一輪車を押さえ込みすぎない。',
                'caution' => 'サドルを戻す拍とペダル位置を決める。',
                'evidence_type' => '既存技一覧を統合した昇級案',
                'source_ids' => ['S01', 'S02'],
                'avatar_path' => 'images/skills/level-36.png',
                'movie_path' => null,
                'is_active' => true,
            ],
            [
                'code' => 'SKL-037',
                'level' => 37,
                'animal' => 'トラ',
                'level_label' => 'トラ級',
                'name' => 'サドル後ろ出し5m',
                'alternate_name' => 'Seat in back 5 m',
                'category' => 'ソロ',
                'performance_type' => 'ソロ',
                'skill_family' => 'サドル操作',
                'promotion_test' => 'サドルを後ろへ出して5m走行する',
                'pass_criteria' => '指定姿勢で5m進み、サドルを戻して走行を続ける',
                'official_reference' => '既存技一覧を統合',
                'min_duration' => 8,
                'default_duration' => 12,
                'max_duration' => 20,
                'showiness' => 4,
                'sync_load' => 1,
                'people' => '1人',
                'trajectory' => '直線',
                'recommended_scene' => '見せ場',
                'description' => 'サドルを後ろへ出して5m走行する。指定姿勢で5m進み、サドルを戻して走行を続ける',
                'tips' => '胸を起こし、サドルを後ろへ抜いても腰を車輪上に置く。',
                'caution' => 'サドル位置が見えにくいため戻し方を段階練習する。',
                'evidence_type' => '既存技一覧を統合した昇級案',
                'source_ids' => ['S01', 'S02'],
                'avatar_path' => 'images/skills/level-37.png',
                'movie_path' => null,
                'is_active' => true,
            ],
            [
                'code' => 'SKL-038',
                'level' => 38,
                'animal' => 'トラ',
                'level_label' => 'トラ級',
                'name' => '180度ターン左右',
                'alternate_name' => 'Left and right 180-degree turns',
                'category' => 'ソロ',
                'performance_type' => 'ソロ',
                'skill_family' => '方向転換',
                'promotion_test' => '左右それぞれの180度ターンを行う',
                'pass_criteria' => '右回り・左回りを各1回成功し、走行を継続する',
                'official_reference' => '既存技一覧を統合',
                'min_duration' => 6,
                'default_duration' => 10,
                'max_duration' => 16,
                'showiness' => 4,
                'sync_load' => 1,
                'people' => '1人',
                'trajectory' => '折返し',
                'recommended_scene' => 'アクセント',
                'description' => '左右それぞれの180度ターンを行う。右回り・左回りを各1回成功し、走行を継続する',
                'tips' => '旋回前に減速し、視線を出口へ先に送る。',
                'caution' => '苦手側でも急に一輪車をねじらない。',
                'evidence_type' => '既存技一覧を統合した昇級案',
                'source_ids' => ['S01', 'S02'],
                'avatar_path' => 'images/skills/level-38.png',
                'movie_path' => null,
                'is_active' => true,
            ],
            [
                'code' => 'SKL-039',
                'level' => 39,
                'animal' => 'トラ',
                'level_label' => 'トラ級',
                'name' => '右スピン3周',
                'alternate_name' => 'Three clockwise spins',
                'category' => 'ソロ',
                'performance_type' => 'ソロ',
                'skill_family' => '回転',
                'promotion_test' => '右回りのスピンを3周行う',
                'pass_criteria' => '決めた円内で3回転し、正面を向いて終了する',
                'official_reference' => '既存技一覧のスピンを段階化',
                'min_duration' => 6,
                'default_duration' => 9,
                'max_duration' => 14,
                'showiness' => 5,
                'sync_load' => 1,
                'people' => '1人',
                'trajectory' => '右小円',
                'recommended_scene' => 'ピーク',
                'description' => '右回りのスピンを3周行う。決めた円内で3回転し、正面を向いて終了する',
                'tips' => '進入速度を整え、肩の高さと小円の中心を保つ。',
                'caution' => '回転域の周囲に十分な空間を確保する。',
                'evidence_type' => '既存技一覧を統合した昇級案',
                'source_ids' => ['S02', 'S03'],
                'avatar_path' => 'images/skills/level-39.png',
                'movie_path' => null,
                'is_active' => true,
            ],
            [
                'code' => 'SKL-040',
                'level' => 40,
                'animal' => 'トラ',
                'level_label' => 'トラ級',
                'name' => '左スピン3周',
                'alternate_name' => 'Three counterclockwise spins',
                'category' => 'ソロ',
                'performance_type' => 'ソロ',
                'skill_family' => '回転',
                'promotion_test' => '左回りのスピンを3周行う',
                'pass_criteria' => '決めた円内で3回転し、正面を向いて終了する',
                'official_reference' => '既存技一覧のスピンを段階化',
                'min_duration' => 6,
                'default_duration' => 9,
                'max_duration' => 14,
                'showiness' => 5,
                'sync_load' => 1,
                'people' => '1人',
                'trajectory' => '左小円',
                'recommended_scene' => 'ピーク',
                'description' => '左回りのスピンを3周行う。決めた円内で3回転し、正面を向いて終了する',
                'tips' => '苦手側でも速度を落としすぎず、視線と肩をそろえる。',
                'caution' => '目まいと接触を避け、回転練習の間隔を空ける。',
                'evidence_type' => '既存技一覧を統合した昇級案',
                'source_ids' => ['S02', 'S03'],
                'avatar_path' => 'images/skills/level-40.png',
                'movie_path' => null,
                'is_active' => true,
            ],
            [
                'code' => 'SKL-041',
                'level' => 41,
                'animal' => 'トラ',
                'level_label' => 'トラ級',
                'name' => 'ペア並走1周',
                'alternate_name' => 'Pair parallel ride',
                'category' => 'ペア',
                'performance_type' => 'ペア',
                'skill_family' => '同期',
                'promotion_test' => '2人で横に並び、アリーナを1周する',
                'pass_criteria' => '決めた間隔を保ち、2人とも途中降車せず1周する',
                'official_reference' => '既存ペア構成を簡略化',
                'min_duration' => 25,
                'default_duration' => 35,
                'max_duration' => 50,
                'showiness' => 3,
                'sync_load' => 3,
                'people' => '2人',
                'trajectory' => '平行周回',
                'recommended_scene' => '導入',
                'description' => '2人で横に並び、アリーナを1周する。決めた間隔を保ち、2人とも途中降車せず1周する',
                'tips' => '前輪より肩のラインをそろえ、共通の進行方向を見る。',
                'caution' => '近づきすぎず、内側と外側の速度差を確認する。',
                'evidence_type' => '既存技一覧を統合した昇級案',
                'source_ids' => ['S04', 'S06'],
                'avatar_path' => 'images/skills/level-41.png',
                'movie_path' => null,
                'is_active' => true,
            ],
            [
                'code' => 'SKL-042',
                'level' => 42,
                'animal' => 'トラ',
                'level_label' => 'トラ級',
                'name' => '手つなぎ1周',
                'alternate_name' => 'Hand-in-hand one-lap ride',
                'category' => 'ペア',
                'performance_type' => 'ペア',
                'skill_family' => '接触',
                'promotion_test' => '2人で手をつないで1周する',
                'pass_criteria' => '手へ体重を預けず、途中降車なしで1周する',
                'official_reference' => '既存ペア構成を簡略化',
                'min_duration' => 25,
                'default_duration' => 35,
                'max_duration' => 50,
                'showiness' => 3,
                'sync_load' => 4,
                'people' => '2人',
                'trajectory' => '平行周回',
                'recommended_scene' => '見せ場',
                'description' => '2人で手をつないで1周する。手へ体重を預けず、途中降車なしで1周する',
                'tips' => '肘を少し曲げ、手の高さと二人の中間点を一定にする。',
                'caution' => '転倒時に手を離す合図を決める。',
                'evidence_type' => '既存技一覧を統合した昇級案',
                'source_ids' => ['S03', 'S04'],
                'avatar_path' => 'images/skills/level-42.png',
                'movie_path' => null,
                'is_active' => true,
            ],
            [
                'code' => 'SKL-043',
                'level' => 43,
                'animal' => 'トラ',
                'level_label' => 'トラ級',
                'name' => '同時アイドリング10回',
                'alternate_name' => 'Ten synchronized idles',
                'category' => 'ペア',
                'performance_type' => 'ペア',
                'skill_family' => '同期',
                'promotion_test' => '2人で同時にアイドリングを10回行う',
                'pass_criteria' => '開始・10回目・終了のタイミングをそろえる',
                'official_reference' => '既存ペア構成を簡略化',
                'min_duration' => 10,
                'default_duration' => 15,
                'max_duration' => 22,
                'showiness' => 4,
                'sync_load' => 4,
                'people' => '2人',
                'trajectory' => '2定点',
                'recommended_scene' => '見せ場',
                'description' => '2人で同時にアイドリングを10回行う。開始・10回目・終了のタイミングをそろえる',
                'tips' => '互いではなく音やカウントに合わせ、往復の向きを決める。',
                'caution' => '同方向かミラーかを事前に統一する。',
                'evidence_type' => '既存技一覧を統合した昇級案',
                'source_ids' => ['S04', 'S06'],
                'avatar_path' => 'images/skills/level-43.png',
                'movie_path' => null,
                'is_active' => true,
            ],
            [
                'code' => 'SKL-044',
                'level' => 44,
                'animal' => 'トラ',
                'level_label' => 'トラ級',
                'name' => '同時バック走行5m',
                'alternate_name' => 'Synchronized backward riding 5 m',
                'category' => 'ペア',
                'performance_type' => 'ペア',
                'skill_family' => '同期',
                'promotion_test' => '2人で並んでバック走行を5m行う',
                'pass_criteria' => '指定間隔を保ち、2人とも途中降車なしで5m進む',
                'official_reference' => '既存ペア構成を短距離化',
                'min_duration' => 8,
                'default_duration' => 12,
                'max_duration' => 20,
                'showiness' => 4,
                'sync_load' => 5,
                'people' => '2人',
                'trajectory' => '平行バック直線',
                'recommended_scene' => '見せ場',
                'description' => '2人で並んでバック走行を5m行う。指定間隔を保ち、2人とも途中降車なしで5m進む',
                'tips' => '確認する肩と走り出す拍をそろえ、肩線で並びを保つ。',
                'caution' => '後方専用レーンと補助者を用意する。',
                'evidence_type' => '既存技一覧を統合した昇級案',
                'source_ids' => ['S04', 'S06'],
                'avatar_path' => 'images/skills/level-44.png',
                'movie_path' => null,
                'is_active' => true,
            ],
            [
                'code' => 'SKL-045',
                'level' => 45,
                'animal' => 'トラ',
                'level_label' => 'トラ級',
                'name' => 'すれ違いクロス',
                'alternate_name' => 'Opposing pass',
                'category' => 'ペア',
                'performance_type' => 'ペア',
                'skill_family' => '交差',
                'promotion_test' => '向かい合って走り、中央ですれ違う',
                'pass_criteria' => '決めた左右を通り、接触せず同じ拍で交差する',
                'official_reference' => '既存ペア構成を統合',
                'min_duration' => 6,
                'default_duration' => 10,
                'max_duration' => 16,
                'showiness' => 4,
                'sync_load' => 5,
                'people' => '2人',
                'trajectory' => '対向直線',
                'recommended_scene' => 'アクセント',
                'description' => '向かい合って走り、中央ですれ違う。決めた左右を通り、接触せず同じ拍で交差する',
                'tips' => '交差点を見続けず、通過後の出口へ視線を置く。',
                'caution' => '通過側と安全余白を固定して低速から練習する。',
                'evidence_type' => '既存技一覧を統合した昇級案',
                'source_ids' => ['S04', 'S06'],
                'avatar_path' => 'images/skills/level-45.png',
                'movie_path' => null,
                'is_active' => true,
            ],
            [
                'code' => 'SKL-046',
                'level' => 46,
                'animal' => 'トラ',
                'level_label' => 'トラ級',
                'name' => '位置交換クロス',
                'alternate_name' => 'Partner switch cross',
                'category' => 'ペア',
                'performance_type' => 'ペア',
                'skill_family' => '交差',
                'promotion_test' => '2人が交差して左右の位置を交換する',
                'pass_criteria' => '接触せず、交換後の基準位置まで走り切る',
                'official_reference' => '既存ペア構成を統合',
                'min_duration' => 8,
                'default_duration' => 12,
                'max_duration' => 20,
                'showiness' => 4,
                'sync_load' => 5,
                'people' => '2人',
                'trajectory' => 'X字・S字',
                'recommended_scene' => '見せ場',
                'description' => '2人が交差して左右の位置を交換する。接触せず、交換後の基準位置まで走り切る',
                'tips' => '交差前後の速度を変えず、出口位置を床目印で決める。',
                'caution' => '出口で再接近しないよう終点を離す。',
                'evidence_type' => '既存技一覧を統合した昇級案',
                'source_ids' => ['S04', 'S06'],
                'avatar_path' => 'images/skills/level-46.png',
                'movie_path' => null,
                'is_active' => true,
            ],
            [
                'code' => 'SKL-047',
                'level' => 47,
                'animal' => 'トラ',
                'level_label' => 'トラ級',
                'name' => '同時ホッピング5回',
                'alternate_name' => 'Five synchronized hops',
                'category' => 'ペア',
                'performance_type' => 'ペア',
                'skill_family' => '同期',
                'promotion_test' => '2人で同時にホッピングを5回行う',
                'pass_criteria' => '開始・5回の着地・終了姿勢をそろえる',
                'official_reference' => '既存ペア構成を簡略化',
                'min_duration' => 5,
                'default_duration' => 8,
                'max_duration' => 12,
                'showiness' => 5,
                'sync_load' => 5,
                'people' => '2人',
                'trajectory' => '2定点',
                'recommended_scene' => 'ピーク',
                'description' => '2人で同時にホッピングを5回行う。開始・5回の着地・終了姿勢をそろえる',
                'tips' => '高さより着地音とタイミングをそろえる。',
                'caution' => '互いの跳躍範囲が重ならない間隔を取る。',
                'evidence_type' => '既存技一覧を統合した昇級案',
                'source_ids' => ['S04', 'S06'],
                'avatar_path' => 'images/skills/level-47.png',
                'movie_path' => null,
                'is_active' => true,
            ],
            [
                'code' => 'SKL-048',
                'level' => 48,
                'animal' => 'トラ',
                'level_label' => 'トラ級',
                'name' => 'ペア8の字走行',
                'alternate_name' => 'Pair figure-eight ride',
                'category' => 'ペア',
                'performance_type' => 'ペア',
                'skill_family' => '走行',
                'promotion_test' => '2人で同じ大きさの8の字を走行する',
                'pass_criteria' => '決めた配置と間隔を保ち、接触せず1周する',
                'official_reference' => '既存ペア構成を簡略化',
                'min_duration' => 18,
                'default_duration' => 26,
                'max_duration' => 40,
                'showiness' => 5,
                'sync_load' => 5,
                'people' => '2人',
                'trajectory' => '並列8の字・ミラー',
                'recommended_scene' => 'ピーク',
                'description' => '2人で同じ大きさの8の字を走行する。決めた配置と間隔を保ち、接触せず1周する',
                'tips' => '交点の通過順、円の大きさ、正面を向く拍を合わせる。',
                'caution' => '同じ交点へ同時に入らない配置から始める。',
                'evidence_type' => '既存技一覧を統合した昇級案',
                'source_ids' => ['S04', 'S06'],
                'avatar_path' => 'images/skills/level-48.png',
                'movie_path' => null,
                'is_active' => true,
            ],
            [
                'code' => 'SKL-049',
                'level' => 49,
                'animal' => 'トラ',
                'level_label' => 'トラ級',
                'name' => 'カノン走行',
                'alternate_name' => 'Riding canon',
                'category' => 'ペア',
                'performance_type' => 'ペア',
                'skill_family' => '時間差',
                'promotion_test' => '同じ走行を4拍ずらして行う',
                'pass_criteria' => '決めた4拍差を開始から終了まで保つ',
                'official_reference' => '既存ペア構成を統合',
                'min_duration' => 12,
                'default_duration' => 18,
                'max_duration' => 28,
                'showiness' => 5,
                'sync_load' => 5,
                'people' => '2人',
                'trajectory' => '同軌道・時間差',
                'recommended_scene' => '盛り上がり',
                'description' => '同じ走行を4拍ずらして行う。決めた4拍差を開始から終了まで保つ',
                'tips' => '先行者の開始位置と後行者の合図を音楽上で固定する。',
                'caution' => '意図した時差とミスが区別できる間隔にする。',
                'evidence_type' => '既存技一覧を統合した昇級案',
                'source_ids' => ['S04', 'S06'],
                'avatar_path' => 'images/skills/level-49.png',
                'movie_path' => null,
                'is_active' => true,
            ],
            [
                'code' => 'SKL-050',
                'level' => 50,
                'animal' => 'トラ',
                'level_label' => 'トラ級',
                'name' => '30秒ペア演技',
                'alternate_name' => 'Thirty-second pair routine',
                'category' => 'ペア',
                'performance_type' => 'ペア',
                'skill_family' => '総合',
                'promotion_test' => '走り出し・ペア技2つ・フィニッシュを含む30秒演技を行う',
                'pass_criteria' => '30～60秒以内で、開始・2つ以上のペア技・終了姿勢を2人でそろえる',
                'official_reference' => '既存演技シミュレーション方針',
                'min_duration' => 30,
                'default_duration' => 40,
                'max_duration' => 60,
                'showiness' => 5,
                'sync_load' => 5,
                'people' => '2人',
                'trajectory' => '自由構成',
                'recommended_scene' => 'フィニッシュ',
                'description' => '走り出し・ペア技2つ・フィニッシュを含む30秒演技を行う。30～60秒以内で、開始・2つ以上のペア技・終了姿勢を2人でそろえる',
                'tips' => '難しい技を増やすより、開始・切替・終了の拍を明確にする。',
                'caution' => '事前に軌道、方向、距離をコメントで共有する。',
                'evidence_type' => '既存技一覧を統合した昇級案',
                'source_ids' => ['U01', 'S04', 'S06'],
                'avatar_path' => 'images/skills/level-50.png',
                'movie_path' => null,
                'is_active' => true,
            ],
        ];

        $skills = array_map(
            static function (array $skill) use ($now): array {
                $skill['source_ids'] = json_encode(
                    $skill['source_ids'],
                    JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES
                );
                $skill['created_at'] = $now;
                $skill['updated_at'] = $now;

                return $skill;
            },
            $skills
        );

        DB::table('skills')->upsert(
            $skills,
            ['code'],
            [
                    'level',
                    'animal',
                    'level_label',
                    'name',
                    'alternate_name',
                    'category',
                    'performance_type',
                    'skill_family',
                    'promotion_test',
                    'pass_criteria',
                    'official_reference',
                    'min_duration',
                    'default_duration',
                    'max_duration',
                    'showiness',
                    'sync_load',
                    'people',
                    'trajectory',
                    'recommended_scene',
                    'description',
                    'tips',
                    'caution',
                    'evidence_type',
                    'source_ids',
                    'avatar_path',
                    'movie_path',
                    'is_active',
                'updated_at',
            ]
        );
    }
}
